'use strict';

const validators = require('../../../../lib/models/validators');
const { NotFoundError } = require('../../../../lib/errors');

const Batch = require('../../../../lib/models/batch');
const FinancialYear = require('../../../../lib/models/financial-year');
const InvoiceLicence = require('../../../../lib/models/invoice-licence');

const { getChargePeriod } = require('../../lib/charge-period');
const crmHelpers = require('./lib/crm-helpers');
const transactionsProcessor = require('./transactions-processor');

const mappers = require('../../mappers');

// Services
const chargeVersionService = require('../../../../lib/services/charge-versions');
const billingVolumesService = require('../../services/billing-volumes-service');

/**
 * Given CRM company data and the charge version being processed,
 * gets an InvoiceLicence instance
 * @param {Object} company - data from CRM
 * @param {ChargeVersion} chargeVersion
 */
const createInvoiceLicence = (chargeVersion) => {
  const invoiceLicence = new InvoiceLicence();
  return invoiceLicence.fromHash({
    licence: chargeVersion.licence
  });
};

/**
 * Creates the invoice data structure for a given charge version year
 * @param {Batch} batch
 * @param {FinancialYear} financialYear
 * @param {String} chargeVersionId
 * @return {Promise<Invoice>}
 */
const processChargeVersionYear = async (batch, financialYear, chargeVersionId) => {
  validators.assertIsInstanceOf(batch, Batch);
  validators.assertIsInstanceOf(financialYear, FinancialYear);
  validators.assertId(chargeVersionId);

  // Load ChargeVersion service model
  const chargeVersion = await chargeVersionService.getByChargeVersionId(chargeVersionId);
  if (!chargeVersion) {
    throw new NotFoundError(`Charge version ${chargeVersionId} not found`);
  }

  // Load all billing volumes relating to the charge elements and financial year
  // For supplementary these could have been generated by a previous TPT batch, not the current batch
  // There could also be multiple billing volumes per element - for summer and winter/all year TPT batches
  const billingVolumes = await billingVolumesService.getVolumesForChargeElements(chargeVersion.chargeElements, financialYear);

  // Get charge period
  const chargePeriod = getChargePeriod(financialYear, chargeVersion);

  // Load company/invoice account/licence holder data from CRM
  const [invoiceAccount] = await crmHelpers.getCRMData(chargeVersion, chargePeriod.startDate);

  // Generate Invoice data structure
  const invoice = mappers.invoice.crmToModel(invoiceAccount);
  invoice.financialYear = financialYear;
  const invoiceLicence = createInvoiceLicence(chargeVersion);
  invoiceLicence.transactions = transactionsProcessor.createTransactions(batch, financialYear, chargeVersion, billingVolumes);
  invoice.invoiceLicences = [invoiceLicence];

  return invoice;
};

exports.processChargeVersionYear = processChargeVersionYear;
