version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
