language: node_js

node_js:
  - "8"

dist: trusty

sudo: required

addons:
  chrome: stable
  postgresql: "9.6"
  code_climate:
    repo_token: $CODE_CLIMATE_REPORTER_ID

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run migrate

script:
  - npm run lint
  - npm run test:travis
  - npm run codecov

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost:5432/travis_ci_test
    - JWT_SECRET=secret
    - JWT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIzNH0.MOREC6-Kszb9bDFw0O1UKywpnkcP-c5cPjASMpjk8Po
    - errbit_key=xyz
    - errbit_server=http://localhost
    - PORT=8001
    - NOTIFY_KEY=somerealnotifykey-00000000-0000-0000-0000-000000000000-00000000-0000-0000-0000-000000000000

#    - TEST_NOTIFY_KEY=sometestnotifykey-00000000-0000-0000-0000-000000000000-00000000-0000-0000-0000-000000000000
