ALTER TABLE water.licence_version_purpose_condition_types
    ADD column display_title varchar;

BEGIN TRANSACTION;
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Aggregate condition link between licences' WHERE code='AGG' AND subcode='LLL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Aggregate condition cross regional link between licences' WHERE code='AGG' AND subcode='LLX';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Aggregate condition licence to purpose between different licences' WHERE code='AGG' AND subcode='LPL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Aggregate condition purpose to purpose within a licence' WHERE code='AGG' AND subcode='PP';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Aggregate condition purpose to purpose between different licences' WHERE code='AGG' AND subcode='PPL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Additional groundwater information dimensions' WHERE code='AGI' AND subcode='DIM';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'By-pass flow' WHERE code='BYPAS' AND subcode='FLOW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Chemical cessation condition' WHERE code='CES' AND subcode='CHE';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Cessation dependant on releases from schemes / other licences' WHERE code='CES' AND subcode='DEP';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Flow cessation condition' WHERE code='CES' AND subcode='FLOW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Groundwater level cessation condition' WHERE code='CES' AND subcode='GWL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Level cessation condition' WHERE code='CES' AND subcode='LEV';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Political cessation condition' WHERE code='CES' AND subcode='POL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Link between split licences' WHERE code='COMB' AND subcode='LINK';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Complex condition' WHERE code='COMP' AND subcode='GEN';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Flow compensation release' WHERE code='COMPR' AND subcode='FLOW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Derogation clause' WHERE code='DEROG' AND subcode='CLAUS';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Fish pass/screen - eel regs SI3344' WHERE code='EEL' AND subcode='REGS';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Filling/emptying to be notified to Agency' WHERE code='FILL' AND subcode='FILL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Filling/emptying season limited' WHERE code='FILL' AND subcode='SEAS';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Inflow control type' WHERE code='INFLO' AND subcode='TYPE';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Inflow rate' WHERE code='INFLR' AND subcode='RATE';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Type of lining' WHERE code='LINTY' AND subcode='TYPE';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Lockable structures required' WHERE code='LOK' AND subcode='OFF';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Maintained flow' WHERE code='MAINT' AND subcode='FLOW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Means of compensation flow release' WHERE code='MCOMP' AND subcode='MEANS';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Non standard quantities cubic metres per fortnight' WHERE code='NSQ' AND subcode='M3FN';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Non standard quantities cubic metres per month' WHERE code='NSQ' AND subcode='M3MO';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Non standard quantities cubic metres per week' WHERE code='NSQ' AND subcode='M3WK';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Non standard quantities' WHERE code='NSQ' AND subcode='PER';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'General conditions' WHERE code='OTH' AND subcode='GEN';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Complex proportional take' WHERE code='PTAK' AND subcode='COMP';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Proportional percentage take' WHERE code='PTAK' AND subcode='PCENT';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Public water supply licensee' WHERE code='PWS' AND subcode='WSL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Rates litres per second' WHERE code='RAT' AND subcode='LPS';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Rates m3 per day' WHERE code='RAT' AND subcode='M3D';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Rates m3 per month' WHERE code='RAT' AND subcode='M3M';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Rates m3 per second' WHERE code='RAT' AND subcode='M3S';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Spray irrigation ban imposed' WHERE code='S57' AND subcode='BANI';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Spray irrigation ban proposed' WHERE code='S57' AND subcode='BANP';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Time limited minimum quantity' WHERE code='TLTD' AND subcode='MINQ';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Time limited self destruct' WHERE code='TLTD' AND subcode='SD';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Time limited variation' WHERE code='TLTD' AND subcode='VAR';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Time Limited Extension of Validity - Full Licence Expiry' WHERE code='TLTD' AND subcode='LEVFL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Time Limited Extension of Validity - Time Limited Variation' WHERE code='TLTD' AND subcode='LEVTL';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Transfer' WHERE code='TRA' AND subcode='TRAN';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Water level monitoring groundwater' WHERE code='WLM' AND subcode='GW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Water level monitoring surface water' WHERE code='WLM' AND subcode='SW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Water quality monitoring groundwater' WHERE code='WQM' AND subcode='GW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Water quality monitoring surface water' WHERE code='WQM' AND subcode='SW';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Water rights trade point' WHERE code='WRT' AND subcode='PNT';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Water rights trade purpose' WHERE code='WRT' AND subcode='PUR';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Water rights trade quantity' WHERE code='WRT' AND subcode='QTY';
UPDATE water.licence_version_purpose_condition_types SET display_title = 'Licensed point falls within another region' WHERE code='XREG' AND subcode='PTS';
COMMIT;