/* Revert our changes */

UPDATE water.scheduled_notification_categories snc
SET scheduled_notification_refs = '{pdf.return_form}'
WHERE snc.category_value = 'returns_paper_forms';

UPDATE water.scheduled_notification_categories snc
SET scheduled_notification_refs = '{returns_reminder_licence_holder_letter,returns_reminder_licence_holder_letter_active_choice,returns_reminder_licence_holder_letter_control,returns_reminder_licence_holder_letter_enforcement_action,returns_reminder_licence_holder_letter_loss_aversion,returns_reminder_primary_user_email,returns_reminder_primary_user_email_active_choice,returns_reminder_primary_user_email_control,returns_reminder_primary_user_email_enforcement_action,returns_reminder_primary_user_email_loss_aversion,returns_reminder_returns_agent_email,returns_reminder_returns_agent_email_active_choice,returns_reminder_returns_agent_email_control,returns_reminder_returns_agent_email_enforcement_action,returns_reminder_returns_agent_email_loss_aversion,returns_reminder_returns_to_letter,returns_reminder_returns_to_letter_active_choice,returns_reminder_returns_to_letter_control,returns_reminder_returns_to_letter_enforcement_action,returns_reminder_returns_to_letter_loss_aversion}'
WHERE snc.category_value = 'returns.reminders';

UPDATE water.scheduled_notification_categories snc
SET scheduled_notification_refs = '{returns_invitation_letter,returns_invitation_licence_holder_letter,returns_invitation_licence_holder_letter_control,returns_invitation_licence_holder_letter_formality,returns_invitation_licence_holder_letter_moral_suasion,returns_invitation_licence_holder_letter_social_norm,returns_invitation_primary_user_email,returns_invitation_primary_user_email_control,returns_invitation_primary_user_email_formality,returns_invitation_primary_user_email_moral_suasion,returns_invitation_primary_user_email_social_norm,returns_invitation_returns_agent_email,returns_invitation_returns_agent_email_control,returns_invitation_returns_agent_email_formality,returns_invitation_returns_agent_email_moral_suasion,returns_invitation_returns_agent_email_social_norm,returns_invitation_returns_to_letter,returns_invitation_returns_to_letter_control,returns_invitation_returns_to_letter_formality,returns_invitation_returns_to_letter_moral_suasion,returns_invitation_returns_to_letter_social_norm}'
WHERE snc.category_value = 'returns.invitations';

UPDATE water.scheduled_notification_categories snc
SET scheduled_notification_refs = '{water_abstraction_alert_resume,water_abstraction_alert_resume_email}'
WHERE snc.category_value = 'waa.resume';

UPDATE water.scheduled_notification_categories snc
SET scheduled_notification_refs = '{water_abstraction_alert_stop,water_abstraction_alert_stop_email}'
WHERE snc.category_value = 'waa.stop';

UPDATE water.scheduled_notification_categories snc
SET scheduled_notification_refs = '{water_abstraction_alert_reduce,water_abstraction_alert_reduce_or_stop,water_abstraction_alert_reduce_or_stop_email,water_abstraction_alert_reduce_email}'
WHERE snc.category_value = 'waa.reduce';

UPDATE water.scheduled_notification_categories snc
SET scheduled_notification_refs = '{water_abstraction_alert_reduce_warning,water_abstraction_alert_reduce_or_stop_warning,water_abstraction_alert_stop_warning,water_abstraction_alert_stop_warning_email,water_abstraction_alert_reduce_or_stop_warning_email,water_abstraction_alert_reduce_warning_email}'
WHERE snc.category_value = 'waa.warning';
