name: Regression tests

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  regression-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x]
    name: Regression Test - Node  v${{ matrix.node-version }}
    steps:
      - name: Checkout water-abstraction-orchestration
        uses: actions/checkout@v2
        with:
          repository: DEFRA/water-abstraction-orchestration
          path: 'water-abstraction-orchestration'
      - name: Orchestrate
        run: |
          bash ./water-abstraction-orchestration/helpers/clone-repos.sh
          echo "List of repositories"
          ls
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install node modules
        run: |
          bash ./water-abstraction-orchestration/helpers/setup.sh
      - name: Setup run time dependecies
        run: |
          bash ./water-abstraction-orchestration/docker/start.sh
          docker ps
          
